### ISSUE TITLE
Keyboard Scroll on mobile?

### ISSUE THREAD

**Issue by sushantshek20** [LucasBassetti/react-simple-chatbot#100] opened 2018-05-29 12:15 UTC
I am using the bot with these props : 
 floating={true}
    opened={true}

the problem is that when its time for the user to type, the keyboard opens automatically and the chat moves up.

is there any way to keep the chat scoll at bottom when the keyboard opens on mobiile devices?

**Comment by PrakashMurugan** [comment] 2018-05-30 10:42
@sushantshek20 I have the same exact issue.

**Comment by LucasBassetti** [comment] 2018-06-02 21:39
What OS are you having this issue? Android?

**Comment by vysakh0** [comment] 2018-06-03 07:27
@LucasBassetti Yes, have this issue in android OS.

**Comment by PrakashMurugan** [comment] 2018-06-04 09:08
Yeah, the issue is in android OS, I have tried in different devices, found to be the same.

**Comment by sushantshek20** [comment] 2018-06-08 09:30
@LucasBassetti the issue is in Android OS and it's really annoying How fast it scrolls the content up! Is there a fix coming anytime soon?

**Comment by LucasBassetti** [comment] 2018-06-08 11:05
Fixed in version `0.3.1`. Sorry for delay!

**Closed by LucasBassetti** 2018-06-08 11:05 UTC

**Comment by PrakashMurugan** [comment] 2018-06-08 11:22
@LucasBassetti Thanks a lot! Please don't be sorry, we owe you for your great work ❤️ 💚 💜
